import "./globals.css"
import React from "react"
import dynamic from "next/dynamic"
import Providers from "@/utils/provider"

dynamic(() => require("bootstrap/dist/js/bootstrap.min.js"), { ssr: false })

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}
